(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a;}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){Object.defineProperty(exports,
"__esModule",{value:true});exports.PyQuestApi=void 0;const Viewport_1=require("../ui/viewport/Viewport");class PyQuestApi{static getInstance(){if(this.instance===undefined)this.instance=new PyQuestApi;return this.instance}constructor(){Viewport_1.Viewport.getInstance()}}exports.PyQuestApi=PyQuestApi},{"../ui/viewport/Viewport":12}],2:[function(require,module,exports){var __createBinding=this&&this.__createBinding||(Object.create?function(o,m,k,k2){if(k2===undefined)k2=k;var desc=Object.getOwnPropertyDescriptor(m,
k);if(!desc||("get"in desc?!m.__esModule:desc.writable||desc.configurable))desc={enumerable:true,get:function(){return m[k]}};Object.defineProperty(o,k2,desc)}:function(o,m,k,k2){if(k2===undefined)k2=k;o[k2]=m[k]});var __exportStar=this&&this.__exportStar||function(m,exports){for(var p in m)if(p!=="default"&&!Object.prototype.hasOwnProperty.call(exports,p))__createBinding(exports,m,p)};Object.defineProperty(exports,"__esModule",{value:true});__exportStar(require("./PyQuestApi"),exports)},{"./PyQuestApi":1}],
3:[function(require,module,exports){var __createBinding=this&&this.__createBinding||(Object.create?function(o,m,k,k2){if(k2===undefined)k2=k;var desc=Object.getOwnPropertyDescriptor(m,k);if(!desc||("get"in desc?!m.__esModule:desc.writable||desc.configurable))desc={enumerable:true,get:function(){return m[k]}};Object.defineProperty(o,k2,desc)}:function(o,m,k,k2){if(k2===undefined)k2=k;o[k2]=m[k]});var __exportStar=this&&this.__exportStar||function(m,exports){for(var p in m)if(p!=="default"&&!Object.prototype.hasOwnProperty.call(exports,
p))__createBinding(exports,m,p)};Object.defineProperty(exports,"__esModule",{value:true});exports.start=start;const PyQuestApi_1=require("./api/PyQuestApi");__exportStar(require("./api/index"),exports);function start(){window.PyQuestApi=PyQuestApi_1.PyQuestApi.getInstance()}start()},{"./api/PyQuestApi":1,"./api/index":2}],4:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.AbstractElement=void 0;class AbstractElement{constructor(){this.children=[];
this.element=this.createElement();this.addChildren();this.addClasses()}addChild(child){this.children.push(child)}addChildren(){}addClass(className){var _a;const classList=(_a=this.element)===null||_a===void 0?void 0:_a.classList;if(classList!==null)classList.add(className)}addClasses(){for(let className of this.defaultClasses())this.addClass(className);for(let child of this.children)child.addClasses()}defaultClasses(){return[]}renderChild(child){if(this.element!==null&&child.element!==null)this.element.appendChild(child.element)}renderChildren(){for(let child of this.children){this.renderChild(child);
child.renderChildren()}}setBackgroundColor(value){this.setStyle("backgroundColor",value)}setBorder(value){this.setStyle("border",value)}setHeight(value){this.setStyle("height",value+"px")}setHeightPct(value){this.setStyle("height",value+"%")}setProperties(){for(let child of this.children)child.setProperties()}setText(text){if(this.element!==null)this.element.textContent=text}setWidth(value){this.setStyle("width",value+"px")}setStyle(name,value){var _a;const style=(_a=this.element)===null||_a===void 0?
void 0:_a.style;if(style!==null)style[name]=value}}exports.AbstractElement=AbstractElement},{}],5:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.BrElement=void 0;const AbstractElement_1=require("./AbstractElement");class BrElement extends AbstractElement_1.AbstractElement{constructor(){super()}createElement(){return document.createElement("br")}}exports.BrElement=BrElement},{"./AbstractElement":4}],6:[function(require,module,exports){Object.defineProperty(exports,
"__esModule",{value:true});exports.DivElement=void 0;const AbstractElement_1=require("./AbstractElement");class DivElement extends AbstractElement_1.AbstractElement{createElement(){return document.createElement("div")}defaultClasses(){return["container-fluid"]}}exports.DivElement=DivElement},{"./AbstractElement":4}],7:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.H3Element=void 0;const AbstractElement_1=require("./AbstractElement");class H3Element extends AbstractElement_1.AbstractElement{constructor(text){super();
this.setText(text)}createElement(){return document.createElement("h3")}}exports.H3Element=H3Element},{"./AbstractElement":4}],8:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.LiElement=void 0;const AbstractElement_1=require("./AbstractElement");class LiElement extends AbstractElement_1.AbstractElement{constructor(text){super();this.setText(text)}createElement(){return document.createElement("li")}defaultClasses(){return["list-group-item"]}}exports.LiElement=
LiElement},{"./AbstractElement":4}],9:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.RootElement=void 0;const AbstractElement_1=require("./AbstractElement");const TopMenuElement_1=require("./TopMenuElement");class RootElement extends AbstractElement_1.AbstractElement{static getInstance(){if(this.instance===undefined)this.instance=new RootElement;return this.instance}constructor(){super();window.onload=()=>{this.onLoad()}}addChildren(){this.addChild(new TopMenuElement_1.TopMenuElement)}createElement(){return null}onLoad(){this.element=
document.body;this.addClasses();this.renderChildren();this.setProperties()}setProperties(){super.setProperties()}}exports.RootElement=RootElement},{"./AbstractElement":4,"./TopMenuElement":10}],10:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.TopMenuElement=void 0;const BrElement_1=require("./BrElement");const DivElement_1=require("./DivElement");const H3Element_1=require("./H3Element");const LiElement_1=require("./LiElement");const UlElement_1=
require("./UlElement");class TopMenuElement extends DivElement_1.DivElement{addChildren(){this.addChild(new H3Element_1.H3Element("Top Menu"));this.addChild(new BrElement_1.BrElement);this.addChild(this.createUlElement())}createUlElement(){const ulElement=new UlElement_1.UlElement;ulElement.addChild(new LiElement_1.LiElement("Projects"));ulElement.addChild(new LiElement_1.LiElement("Editor"));ulElement.addChild(new LiElement_1.LiElement("Transcript"));ulElement.addChild(new LiElement_1.LiElement("Board"));
ulElement.addChild(new LiElement_1.LiElement("Status"));ulElement.addChild(new LiElement_1.LiElement("Login"));ulElement.addChild(new LiElement_1.LiElement("Help"));return ulElement}}exports.TopMenuElement=TopMenuElement},{"./BrElement":5,"./DivElement":6,"./H3Element":7,"./LiElement":8,"./UlElement":11}],11:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.UlElement=void 0;const AbstractElement_1=require("./AbstractElement");class UlElement extends AbstractElement_1.AbstractElement{createElement(){return document.createElement("ul")}defaultClasses(){return["list-group"]}}
exports.UlElement=UlElement},{"./AbstractElement":4}],12:[function(require,module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.Viewport=void 0;const RootElement_1=require("../core/elements/RootElement");class Viewport{static getInstance(){if(this.instance===undefined)this.instance=new Viewport;return this.instance}constructor(){this.rootElement=RootElement_1.RootElement.getInstance();console.log("VIEWPORT");window.X=this}}exports.Viewport=Viewport},{"../core/elements/RootElement":9}]},
{},[3]);
